version: '3.9'

volumes:
  DB_DATA:

services:
  db:
    image: "postgres:15-alpine"
    restart: "no"
    ports:
      - "5314:5432"
    environment:
      POSTGRES_USER: spotify_gin
      POSTGRES_PASSWORD: 123456
      PGPASSWORD: 123456
      POSTGRES_DB: spotify_gin
      PGDATA: /db_data
    volumes:
      - DB_DATA:/db_data

  redis:
    image: redis:7.2-alpine
    expose:
      - "6378:6378"
    entrypoint: redis-server --bind 0.0.0.0 --port 6378
    network_mode: host

  swagger:
    image: ghcr.io/swaggo/swag:latest
    volumes:
      - ./src:/code
    entrypoint: swag init
