version: '3.9'

volumes:
  DB_DATA:

networks:
  BACKEND:

services:
  db:
    image: "postgres:15-alpine"
    restart: "no"
    environment:
      POSTGRES_USER: spotify_gin
      POSTGRES_PASSWORD: 123456
      PGPASSWORD: 123456
      POSTGRES_DB: spotify_gin
      PGDATA: /db_data
    volumes:
      - DB_DATA:/db_data
    networks:
      - BACKEND


  redis:
    image: redis:7.2-alpine
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 2s
      retries: 10
    networks:
      - BACKEND


  spotify_gin:
    build:
      context: .
      dockerfile: deploy/Dockerfile
    restart: "no"
    volumes:
      - ./src:/code/
    environment:
      DB_HOST: db
      DB_USER: spotify_gin
      DB_PASS: 123456
      DB_NAME: spotify_gin
      DB_PORT: 5432
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - db
      - redis
    networks:
      - BACKEND

  nginx:
    image: nginx:1.17.8-alpine
    ports:
      - "80:80"
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spotify_gin
    networks:
      - BACKEND
